repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./examples/complete"]

  - repo: local
    hooks:
      - id: Fetch remote template
        name: Fetch template
        entry: bash -c "git remote add template https://github.com/adexltd/terraform-aws-module-template.git || git fetch --all && git merge template/main --allow-unrelated-histories --autostash"
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-ast
        - id: double-quote-string-fixer
        - id: detect-private-key
        - id: debug-statements
        - id: requirements-txt-fixer
        - id: check-json

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.86.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_providers_lock
      - id: terraform_checkov
      - id: terraform_trivy
        args:
        - --args=--skip-files "**/main.tf"
      - id: terraform_validate
      - id: terraform_tflint
      - id: infracost_breakdown
        args:
         - --args=--path=./examples/complete
        verbose: true
